version: '3'
services:
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
      - "433:433"
    environment:
      APP_NAME: php-fpm
    volumes:
      - ./src:/var/www/
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/nginx/logs:/var/log/nginx

  php-fpm:
    build:
      context: ./Docker/php-fpm
    volumes:
      - ./src:/var/www
      - ./Docker/app/php.ini:/usr/local/etc/php/custom.d

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: yii
      POSTGRES_USER: yii
    ports:
      - '5432:5432'
    volumes:
      - ./Docker/pgsql:/var/lib/pgsql
